# Generated by Django 5.0.4 on 2025-03-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('credit_history_length', models.IntegerField()),
                ('historical_defaults', models.IntegerField()),
                ('loan_amount', models.IntegerField()),
                ('loan_grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=50)),
                ('loan_interest_rate', models.IntegerField()),
                ('loan_intent', models.CharField(choices=[('DEBTCONSOLIDATION', 'Debt Consolidation'), ('EDUCATION', 'Education'), ('HOMEIMPROVEMENT', 'Home Improvement'), ('MEDICAL', 'Medical'), ('PERSONAL', 'Personal'), ('VENTRUE', 'Venture')], max_length=50)),
                ('loan_percent_income', models.IntegerField()),
                ('person_age', models.IntegerField()),
                ('person_employment_length', models.IntegerField()),
                ('person_home_ownership', models.CharField(choices=[('MORTGAGE', 'Mortgage'), ('OTHER', 'Other'), ('OWN', 'Own'), ('RENT', 'Rent')], max_length=50)),
                ('person_income', models.IntegerField()),
                ('will_default', models.CharField(default=None, max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
